### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by ashakoen** [aredden/torch-cublas-hgemm#2]
Prior to seeing your note in the README on https://github.com/aredden/flux-fp8-api, I went ahead and tried to install this because it was in the requirements.txt for flux-fp8-api, but got an error on Ubuntu 22.04. I ended up having to change line 31 in cublas_ops/__init__.py as follows:

    def get(cls, __name: str, device: torch.device) -> torch.Any:

to this:

    def get(cls, __name: str, device: torch.device) -> Any:

and I had to include:
```
from typing import Any
```

I'm way out of my league here, but wanted to report it all the same. Thanks!

**Comment by aredden** [comment]
Ah thanks! I'll change this.
